apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-kustomize
  namespace: argocd
spec:
  destination:
    namespace: myapp-kustomize-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize
    repoURL: https://github.com/aditug/argocd-example
    targetRevision: main
    kustomize:
      namePrefix: staging-
      commonLabels:
        app: demo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true